import { SpeedInsights } from "@vercel/speed-insights/react"
import { Analytics } from "@vercel/analytics/react"

import { Header } from "../widgets/header/header";
import { Sidebar } from "../widgets/sidebar/sidebar";
import { Footer } from "../widgets/footer/footer";
import { FastNavigation } from "../features/fastNav/fastNav";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
          <hr />
          <Sidebar />
          <main>
            {children}
          </main>
          <hr />
          <Footer />
        <FastNavigation />
        <SpeedInsights />
        <Analytics />
      </body>
    </html>
  )
}
